services:
  # http://localhost:15672
  # https://hub.docker.com/_/rabbitmq
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    # expose:
    #   - "5672" # service port
    ports:
      - "5672:5672"
      - "15672:15672" # management port
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 3

  # https://hub.docker.com/_/postgres
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tv-commercial-recognition
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U postgres -d tv-commercial-recognition || exit 1"
        ]
      interval: 10s
      timeout: 5s
      retries: 3

  # celery:
  #   image: celery:5.0.5
  #   command: celery -A my_app worker -l info -Q celery -n celery@%h
  #   environment:
  #     CELERY_BROKER_URL: amqp://guest:guest@rabbitmq:5672//
  #     CELERY_RESULT_BACKEND: redis://redis:6379/0
  #     CELERY_TASK_SERIALIZER: json
  #     CELERY_RESULT_SERIALIZER: json
  #     CELERY_ACCEPT_CONTENT: json
  #     CELERY_TIMEZONE: Europe/Moscow
  #     CELERY_ENABLE_UTC: true
  #     CELERYD_PREFETCH_MULTIPLIER: 1
  #     CELERYD_MAX_TASKS_PER_CHILD: 1
  #     CELERYD_TASK_TIME_LIMIT: 600
  #     CELERYD_TASK_SOFT_TIME_LIMIT: 600
  #     CELERYD_CONCURRENCY: 1
  #     CELERYD_POOL: solo
  #     CELERYD_HIJACK_ROOT_LOGGER: false
  #     CELERYD_LOG_COLOR: false
  #     CELERYD_LOG_FORMAT: "[%(asctime)s: %(levelname)s/%(processName)s] %(message)s"
  #     CELERYD_TASK_LOG_FORMAT: "[%(asctime)s: %(levelname)s/%(processName)s] %(task_name)s[%(task_id)s]: %(message)s"
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  #     redis:
  #       condition: service_healthy

  # http://localhost:5050
  # https://hub.docker.com/r/dpage/pgadmin4
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin:/var/lib/pgadmin
    # healthcheck:
    #   test:
    #     [
    #       "CMD-SHELL",
    #       "wget --tries 1 --spider http://0.0.0.0:5050/login || exit"
    #     ]
    #   interval: 10s
    #   timeout: 3s
    #   retries: 3

  # http://localhost:5555
  # https://hub.docker.com/r/mher/flower
  flower:
    image: mher/flower:2.0.1
    command: celery flower -A tasks --address=0.0.0.0 --port=5555
    environment:
      FLOWER_ADDRESS: 0.0.0.0
      FLOWER_PORT: 5555
      CELERY_BROKER_URL: amqp://guest:guest@rabbitmq:5672//
      FLOWER_PURGE_OFFLINE_WORKERS: 60
      FLOWER_UNAUTHENTICATED_API: true
    ports:
      - "5555:5555"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --tries 1 --spider http://0.0.0.0:5555/healthcheck || exit"
        ]
      interval: 10s
      timeout: 3s
      retries: 3
    depends_on:
      rabbitmq:
        condition: service_healthy

volumes:
  rabbitmq:
  postgres:
  pgadmin:
